name: NewPlugin
version: '${project.version}'
main: de.tobiaswild.newplugin.Main
api-version: 1.18
authors: [tobiaswild]
website: https.//github.com/tobiaswild/
commands:
    backpack:
        aliases:
            - bp
            - rucksack
        description: open the backpack
    clearchat:
        description: Lösche den Chat
        aliases:
            - cc
    enderchest:
        description: Siehe dir eine Enderchest an
        aliases:
            - ec
    fly:
        description: Lässt dich im Survival Mode fliegen
    freeze:
        description: Lässt dich Spieler einfrieren
    gamemode:
        description: Ändere deinen Spielmodus
        aliases:
            - gm
    heal:
        description: Heile dich oder eine anderen Spieler
    ip:
        description: Zeigt dir deine IP-Adresse
    ping:
        description: Zeigt dir deine Ping
    position:
        aliases:
            - pos
        description: pos
    timer:
        description: controll the timer
    top:
        description: Teleportiere dich an die Oberfläche
    vanish:
        aliases:
            - v
        description: Versteckt dich vor anderen Spielern
    see:
        description: see everything
