name: NewPlugin
version: '${project.version}'
main: de.tobiaswild.newplugin.Main
api-version: 1.18
authors: [tobiaswild]
website: https.//github.com/tobiaswild/
commands:
    back:
        description: Go back to you death position
    backpack:
        aliases:
            - bp
            - rucksack
        description: open the backpack
    build:
        description: switch between survival and creative mode.
    clearchat:
        aliases:
            - cc
        description: Lösche den Chat
    enderchest:
        aliases:
            - ec
        description: Siehe dir eine Enderchest an
    fly:
        description: Go on a big trip with fly
    freeze:
        description: freeze a player
    gamemode:
        aliases:
            - gm
        description: Ächange your gamemode
    heal:
        description: Heal a player
    ip:
        description: Zeigt dir deine IP-Adresse
    ping:
        description: Zeigt dir deine Ping
    position:
        aliases:
            - pos
        description: pos
    timer:
        description: controll the timer
    top:
        description: Teleportiere dich an die Oberfläche
    vanish:
        aliases:
            - v
        description: Versteckt dich vor anderen Spielern
    see:
        description: see everything
